apiVersion: v1
kind: Secret
metadata:
  name: user-api-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "Server=%s;Port=%s;Database=%s;User Id=%s;Password=%s;" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword | b64enc | quote }}
