apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-user-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ .Values.ingress.path }}
        backend:
          service:
            name: {{ include "user-api-chart.fullname" . }}
            port:
              number: 9000