apiVersion: v2
name: user-api-chart
description: A user API Helm chart for Kubernetes

type: application

version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: postgresql
    alias: postgresql
    version: 10.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - user-api-database