replicaCount: 2

image:
  repository: agvozdevdev/otus-user-api
  tag: latest

service:
  type: NodePort
  port: 9000
  targetPort: 8000

ingress:
  host: arch.homework
  path: /otusapp/gvozdev($|/)(.*)

postgresql:
  enable: true
  postgresqlUsername: agvozdev
  postgresqlPassword: 123qwe
  postgresqlDatabase: otus
  service:
    port: "5432"
  