replicaCount: 2

image:
  repository: agvozdevdev/otus-user-api
  tag: latest

service:
  type: NodePort
  port: 8000

postgresql:
  enable: true
  postgresqlUsername: agvozdev
  postgresqlPassword: 123qwe
  postgresqlDatabase: otus
  service:
    port: "5432"
  